# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: ssh_builder 0.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "ssh_builder"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Pierce Moore"]
  s.date = "2014-07-09"
  s.description = "Ruby gem for dynamically building and maintaining your SSH config file."
  s.email = "me@prex.io"
  s.executables = ["ssh_builder"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    "lib/build_script.rb",
    "lib/ssh_builder/app.rb",
    "lib/ssh_builder/aws.rb",
    "lib/ssh_builder/config/config_provider.rb",
    "lib/ssh_builder/config/credentials.rb",
    "lib/ssh_builder/config/personal.rb",
    "lib/ssh_builder/config/ssh.rb",
    "lib/ssh_builder/credentials.rb",
    "lib/ssh_builder/error/aws_credential_error.rb",
    "lib/ssh_builder/helpers.rb",
    "lib/ssh_builder/templates/credentials.mustache",
    "lib/ssh_builder/templates/credentials.rb",
    "lib/ssh_builder/templates/personal.mustache",
    "lib/ssh_builder/templates/personal.rb",
    "lib/ssh_builder/templates/ssh.mustache",
    "lib/ssh_builder/templates/ssh.rb",
    "lib/ssh_builder/templates/template_provider.rb",
    "lib/ssh_builder/utils/autoload.rb",
    "lib/ssh_builder/utils/colorizer.rb",
    "lib/ssh_builder/utils/fs.rb",
    "lib/ssh_builder/utils/log.rb",
    "lib/ssh_builder/utils/signals.rb",
    "lib/ssh_builder/utils/step.rb"
  ]
  s.homepage = "http://github.com/rex/ssh_builder"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.3.0"
  s.summary = "Ruby gem for dynamically building and maintaining your SSH config file."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<colorize>, [">= 0"])
      s.add_runtime_dependency(%q<aws-sdk>, [">= 0"])
      s.add_runtime_dependency(%q<coveralls>, [">= 0"])
      s.add_runtime_dependency(%q<mustache>, [">= 0"])
      s.add_runtime_dependency(%q<no_require>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<colorize>, [">= 0"])
      s.add_dependency(%q<aws-sdk>, [">= 0"])
      s.add_dependency(%q<coveralls>, [">= 0"])
      s.add_dependency(%q<mustache>, [">= 0"])
      s.add_dependency(%q<no_require>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<colorize>, [">= 0"])
    s.add_dependency(%q<aws-sdk>, [">= 0"])
    s.add_dependency(%q<coveralls>, [">= 0"])
    s.add_dependency(%q<mustache>, [">= 0"])
    s.add_dependency(%q<no_require>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

